# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Number-RGB
version:      1.1
version_from: lib/Number/RGB.pm
installdirs:  site
requires:
    Attribute::Handlers:           0
    Class::Accessor::Fast:         0
    Params::Validate:              0
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
